`undef COMMON_CELLS_REGISTERS_SVH_
`undef NO_SYNOPSYS_FF
`undef REG_DFLT_CLK
`undef REG_DFLT_RST
`undef FF
`undef FFAR
`undef FFARN
`undef FFSR
`undef FFSRN
`undef FFNR
`undef FFL
`undef FFLAR
`undef FFLARN
`undef FFLSR
`undef FFLSRN
`undef FFLARNC
`undef FFARNC
`undef FFLNR
