#!/usr/bin/env python3
"""Import one DORY NE16 layer's raw tensors into a Chipyard test fixture."""

import argparse
import hashlib
from pathlib import Path


def parse_expected(path: Path):
    values = []
    for token in path.read_text().replace(',', ' ').split():
        value = int(token)
        if not 0 <= value <= 255:
            raise ValueError(f"expected output contains non-uint8 value {value}")
        values.append(value)
    return bytes(values)


def format_array(name, data):
    lines = [f"const uint8_t {name}[{len(data)}] = {{"]
    for offset in range(0, len(data), 16):
        chunk = data[offset:offset + 16]
        lines.append("    " + ", ".join(f"0x{value:02x}" for value in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--weights", required=True, type=Path)
    parser.add_argument("--expected", required=True, type=Path)
    parser.add_argument("--output-c", required=True, type=Path)
    parser.add_argument("--output-h", required=True, type=Path)
    parser.add_argument("--dory-commit", default="unknown")
    parser.add_argument("--config", default="unknown")
    args = parser.parse_args()

    input_data = args.input.read_bytes()
    weight_blob = args.weights.read_bytes()
    expected_data = parse_expected(args.expected)

    if len(input_data) != 32 * 32 * 16:
        raise ValueError(f"expected 16384 input bytes, got {len(input_data)}")
    if len(weight_blob) != 2304 + 64 + 64:
        raise ValueError(f"expected 2432 weight bytes, got {len(weight_blob)}")
    if len(expected_data) != 32 * 32 * 16:
        raise ValueError(f"expected 16384 output bytes, got {len(expected_data)}")

    weights = weight_blob[:2304]
    scale = weight_blob[2304:2368]
    bias = weight_blob[2368:2432]

    args.output_h.parent.mkdir(parents=True, exist_ok=True)
    args.output_c.parent.mkdir(parents=True, exist_ok=True)
    args.output_h.write_text("""#ifndef NE16_DORY_LAYER_DATA_H
#define NE16_DORY_LAYER_DATA_H

#include <stddef.h>
#include <stdint.h>

#define NE16_DORY_INPUT_BYTES 16384
#define NE16_DORY_WEIGHTS_BYTES 2304
#define NE16_DORY_SCALE_BYTES 64
#define NE16_DORY_BIAS_BYTES 64
#define NE16_DORY_OUTPUT_BYTES 16384

extern const uint8_t ne16_dory_input[NE16_DORY_INPUT_BYTES];
extern const uint8_t ne16_dory_weights[NE16_DORY_WEIGHTS_BYTES];
extern const uint8_t ne16_dory_scale[NE16_DORY_SCALE_BYTES];
extern const uint8_t ne16_dory_bias[NE16_DORY_BIAS_BYTES];
extern const uint8_t ne16_dory_expected[NE16_DORY_OUTPUT_BYTES];

#endif
""")

    digest = lambda data: hashlib.sha256(data).hexdigest()
    comment = """/* Generated by import-dory-ne16-layer.py.\n * DORY commit: %s\n * DORY config: %s\n * input sha256: %s\n * weights sha256: %s\n * expected sha256: %s\n */\n""" % (
        args.dory_commit,
        args.config,
        digest(input_data),
        digest(weight_blob),
        digest(expected_data),
    )
    source = comment + '#include "ne16_dory_layer_data.h"\n\n'
    source += format_array("ne16_dory_input", input_data) + "\n\n"
    source += format_array("ne16_dory_weights", weights) + "\n\n"
    source += format_array("ne16_dory_scale", scale) + "\n\n"
    source += format_array("ne16_dory_bias", bias) + "\n\n"
    source += format_array("ne16_dory_expected", expected_data) + "\n"
    args.output_c.write_text(source)


if __name__ == "__main__":
    main()
